In [1]:
from typing import Dict, List, Tuple
import numpy as np
from scipy.stats import mannwhitneyu, norm

In [16]:
rng = np.random.default_rng()
alfa = rng.random(10)
bravo = rng.random(10)

In [20]:
from scipy.stats import rankdata

In [29]:
ranks = rankdata(np.concatenate((alfa, bravo)))
alfaranks = ranks[0 : len(alfa)]
bravoranks = ranks[len(alfa) : len(alfa) + len(bravo)]

In [32]:
alfa

array([0.54441518, 0.3134845 , 0.03796162, 0.04965201, 0.2034255 ,
       0.28659695, 0.08645109, 0.92232864, 0.40719464, 0.98288992])

In [30]:
alfaranks

array([12.,  7.,  1.,  2.,  4.,  6.,  3., 19.,  9., 20.])

In [33]:
bravo

array([0.57720307, 0.46911575, 0.58278773, 0.8573419 , 0.62765879,
       0.23039218, 0.65105176, 0.762632  , 0.37119905, 0.43005886])

In [31]:
bravoranks

array([13., 11., 14., 18., 15.,  5., 16., 17.,  8., 10.])

In [48]:
alfasum = np.sum(alfaranks)
bravosum = np.sum(bravoranks)

In [49]:
alfaU = alfasum - (len(alfa) * (len(alfa) - 1)) / 2

In [50]:
bravoU = bravosum - (len(bravo) * (len(bravo) - 1)) / 2

In [51]:
min(alfaU, bravoU)

38.0

In [52]:
from sklearn.metrics import auc

In [55]:
auc(np.sort(alfa), np.sort(bravo))

0.5905831231447757

In [58]:
from scipy.stats import mannwhitneyu

In [59]:
mannwhitneyu(alfa, bravo)

MannwhitneyuResult(statistic=28.0, pvalue=0.05205494483011341)

In [63]:
from scipy.stats import norm

ct1 = len(alfa)  # items in dataset 1
ct2 = len(bravo)  # items in dataset 2
alpha = 0.05  # 95% confidence interval
N = norm.ppf(1 - alpha / 2)  # percent point function - inverse of cdf

# The confidence interval for the difference between the two population
# medians is derived through these nxm differences.
diffs = sorted([i - j for i in alfa for j in bravo])

# For an approximate 100(1-a)% confidence interval first calculate K:
k = int(round(ct1 * ct2 / 2 - (N * (ct1 * ct2 * (ct1 + ct2 + 1) / 12) ** 0.5)))

# The Kth smallest to the Kth largest of the n x m differences
# ct1 and ct2 should be > ~20
CI = (diffs[k], diffs[len(diffs) - k])

In [64]:
CI

(-0.4491475010345879, 0.08309232002223887)

In [67]:
np.nan

nan

In [80]:
from numba import jit

In [83]:
sorted([i - j for i in alfa for j in bravo])

[-0.8193802815591948,
 -0.807689887747318,
 -0.7708908106322273,
 -0.7246703850775669,
 -0.71297999126569,
 -0.6761809141505993,
 -0.6539163987005543,
 -0.6130901440337834,
 -0.6013997502219065,
 -0.5896971736461641,
 -0.5780067798342873,
 -0.5707449444408993,
 -0.5646006731068158,
 -0.5592065022189263,
 -0.5448261160156284,
 -0.5438573975162159,
 -0.5412077027191966,
 -0.5392414556077534,
 -0.5331357222037515,
 -0.5275510617958765,
 -0.4963366450886608,
 -0.49075198468078585,
 -0.4760350479592713,
 -0.45014725357542484,
 -0.4491475010345879,
 -0.4476262611751428,
 -0.43115413405811853,
 -0.4242332907875236,
 -0.41946374024624167,
 -0.3920972410745519,
 -0.382664663131151,
 -0.38040684726267504,
 -0.3793622331569878,
 -0.37377757274911283,
 -0.3644548069154878,
 -0.35543735709379687,
 -0.34360777014758437,
 -0.3410618365278686,
 -0.3375672599908044,
 -0.33323743204371015,
 -0.3215470382318333,
 -0.31417428960318516,
 -0.31292671347668966,
 -0.2961907788973328,
 -0.29060611848945783,
 -

In [77]:
len(np.sort(np.ediff1d((alfa, bravo)).flatten()))

19

In [2]:
%store -r alfa

In [3]:
%store -r beta

In [4]:
labels = alfa
values = beta

In [5]:
posii = labels[labels > 0]
negii = labels[labels <= 0]
posn = len(posii)
negn = len(negii)
posval = values[posii.index]
negval = values[negii.index]

In [6]:
posn

54

In [7]:
negn

5690

In [8]:
if posn > 0 & negn > 0:
    statistic, pvalue = mannwhitneyu(posval, negval, alternative="greater")
    conf_int_low, conf_int_high = mannwhitneyu_conf_int(posval, negval)
    res = {
        "low": conf_int_low,
        "high": conf_int_high,
        "auc": (statistic / (posn * negn)),
        "pval": pvalue,
    }
else:
    res = {"auc": 0.5, "pval": np.nan}

In [9]:
res

{'auc': 0.5, 'pval': nan}

In [11]:
(posn > 0 and negn > 0)

True

In [15]:
and

Object `and` not found.
