In [1]:
import numpy as np
import pandas as pd

In [2]:
mat = np.random.rand(60,60)

In [5]:
pd.DataFrame(mat).head()

0         1         2         3         4         5         6   \
0  0.230649  0.510456  0.797957  0.283650  0.094107  0.048148  0.428336   
1  0.798349  0.194357  0.584708  0.584177  0.730505  0.614449  0.486000   
2  0.007373  0.733290  0.826999  0.276844  0.558758  0.795357  0.738793   
3  0.590091  0.669683  0.736043  0.757996  0.255992  0.875288  0.750346   
4  0.789904  0.762382  0.653069  0.721010  0.481980  0.563571  0.932858   

         7         8         9   ...        50        51        52        53  \
0  0.479854  0.205250  0.983521  ...  0.497288  0.538336  0.104515  0.013483   
1  0.188751  0.371087  0.933600  ...  0.142541  0.392668  0.742905  0.884999   
2  0.880608  0.367811  0.433135  ...  0.878977  0.823951  0.416095  0.742772   
3  0.631577  0.985126  0.406014  ...  0.171710  0.593819  0.980749  0.573778   
4  0.814338  0.871004  0.702990  ...  0.373880  0.651018  0.928458  0.124612   

         54        55        56        57        58        59  
0  0.221553  0.631001  0.431578  0.918983  0.871142  0.240459  
1  0.258044  0.252571  0.834405  0.921220  0.793758  0.340165  
2  0.857250  0.664119  0.597360  0.330618  0.781718  0.397461  
3  0.845909  0.898673  0.924065  0.989210  0.800227  0.131212  
4  0.566733  0.501322  0.926975  0.393131  0.297343  0.252808  

[5 rows x 60 columns]

In [6]:
np.linalg.norm(mat)

34.773939057275896

In [7]:
import scipy as sp

In [10]:
sp.linalg.norm(mat)

AttributeError: module 'scipy' has no attribute 'linalg'

In [11]:
from scipy.linalg import norm

In [13]:
norm(mat, axis=0)

array([4.56217763, 4.84908283, 4.39313837, 4.37907728, 4.35158646,
       4.64670736, 4.83667594, 4.47930532, 4.40927911, 4.78507587,
       4.28397912, 4.92719246, 4.38170576, 4.58926331, 4.57710253,
       4.30931461, 4.30256804, 4.13138489, 4.17527665, 5.14333502,
       4.4478124 , 4.35377069, 4.34187332, 4.75910791, 4.00226836,
       4.15375751, 4.4924019 , 4.51593658, 4.73988689, 4.67560633,
       4.35726148, 4.07047419, 4.18859295, 4.99149355, 4.62201465,
       4.68427908, 4.60199447, 4.51130085, 4.19124898, 4.66570883,
       4.85595012, 4.38674797, 4.09670783, 4.2001261 , 4.82675776,
       4.64916654, 4.49659124, 4.46809667, 4.47535753, 4.17034018,
       4.18993369, 4.02511436, 4.39882832, 4.25325448, 4.55883866,
       4.48717536, 4.75634882, 4.39963062, 5.00096339, 4.33063227])

In [14]:
mat2 = np.random.rand(6,6)

In [26]:
mat3 = pd.read_csv("/Users/milessmith/workspace/PLIER/randmat.csv",index_col=0)

In [27]:
mat3

V1        V2        V3        V4        V5        V6
1 -0.408441 -0.882143 -1.406640  0.261968  1.529155 -1.288191
2  1.711693  0.849008  0.874837  2.565819  1.069816  1.050955
3 -0.428506 -0.746334  1.254270  1.121962 -1.296201 -0.397341
4 -0.457917 -0.491485 -0.820537 -0.747517 -1.734600 -0.927167
5  0.273810 -1.771688 -0.629742 -0.157095  1.869177 -0.514145
6  1.410448  0.414870 -0.099260 -0.124593  0.758561  0.231126

In [33]:
mat3.apply(lambda x: norm(x), axis=1)

1    2.643863
2    3.639848
3    2.326078
4    2.356222
5    2.719057
6    1.678002
dtype: float64

In [34]:
from scipy import stats

In [52]:
np.var(mat3, axis=0)

V1    0.803100
V2    0.742949
V3    0.880478
V4    1.181373
V5    1.906228
V6    0.588672
dtype: float64

In [53]:
?np.var

Signature:
np.var(
    a,
    axis=None,
    dtype=None,
    out=None,
    ddof=0,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Docstring:
Compute the variance along the specified axis.

Returns the variance of the array elements, a measure of the spread of a
distribution.  The variance is computed for the flattened array by
default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Array containing numbers whose variance is desired.  If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the variance is computed.  The default is to
    compute the variance of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a variance is performed over multiple axes,
    instead of a single axis or all the axes as before.
dtype : data-type, optional
    Type to use in computing the variance.  For arrays of integer type
    the default is `float64`; for arra

In [76]:
np.std(mat3,axis=1, ddof=1)

1    1.112432
2    0.671366
3    1.036366
4    0.464986
5    1.204095
6    0.582525
dtype: float64

In [ ]:
(x - Rfast::rowmeans(x)) / matrixStats::rowSds(x)

In [86]:
def rowNorm(mat):
    return mat.apply(lambda x: (x - np.mean(x))/np.std(x, ddof=1), axis=1)

In [82]:
np.std(mat3, axis=1,ddof=1)

1    1.112432
2    0.671366
3    1.036366
4    0.464986
5    1.204095
6    0.582525
dtype: float64

In [87]:
rowNorm(mat3)

V1        V2        V3        V4        V5        V6
1 -0.038408 -0.464233 -0.935719  0.564244  1.703358 -0.829242
2  0.533249 -0.751722 -0.713249  1.805470 -0.422827 -0.450921
3 -0.334323 -0.640998  1.289405  1.161739 -1.171571 -0.304252
4  0.871611  0.799420  0.091760  0.248797 -1.874028 -0.137559
5  0.356083 -1.342702 -0.394317 -0.001784  1.681034 -0.298314
6  1.679908 -0.029164 -0.911752 -0.955240  0.560838 -0.344591

In [84]:
mat3.apply(lambda x: (x - np.mean(x))/np.std(x, ddof=1), axis=1)

V1        V2        V3        V4        V5        V6
1 -0.038408 -0.464233 -0.935719  0.564244  1.703358 -0.829242
2  0.533249 -0.751722 -0.713249  1.805470 -0.422827 -0.450921
3 -0.334323 -0.640998  1.289405  1.161739 -1.171571 -0.304252
4  0.871611  0.799420  0.091760  0.248797 -1.874028 -0.137559
5  0.356083 -1.342702 -0.394317 -0.001784  1.681034 -0.298314
6  1.679908 -0.029164 -0.911752 -0.955240  0.560838 -0.344591

In [88]:
mat3

V1        V2        V3        V4        V5        V6
1 -0.408441 -0.882143 -1.406640  0.261968  1.529155 -1.288191
2  1.711693  0.849008  0.874837  2.565819  1.069816  1.050955
3 -0.428506 -0.746334  1.254270  1.121962 -1.296201 -0.397341
4 -0.457917 -0.491485 -0.820537 -0.747517 -1.734600 -0.927167
5  0.273810 -1.771688 -0.629742 -0.157095  1.869177 -0.514145
6  1.410448  0.414870 -0.099260 -0.124593  0.758561  0.231126

In [101]:
mat3_svd = np.linalg.svd(mat3)

In [102]:
mat3_svd

(array([[-0.14411704,  0.61701678,  0.28221381,  0.53776098,  0.34937657,
         -0.32806261],
        [ 0.83149661, -0.01776281,  0.22807868,  0.37114008, -0.0633739 ,
          0.33840327],
        [-0.01145209, -0.35357981,  0.80611018, -0.14618208, -0.1905599 ,
         -0.40908956],
        [-0.4741066 , -0.17193955,  0.08526058,  0.58265414, -0.51714712,
          0.36257878],
        [-0.03115491,  0.66340457,  0.28083572, -0.44505531, -0.4138772 ,
          0.33269578],
        [ 0.24892734,  0.15584373, -0.36384582,  0.1189071 , -0.63156251,
         -0.60692176]]),
 array([4.28716297, 3.8044636 , 2.31661887, 1.30233026, 1.15503533,
        0.39911119]),
 array([[ 0.47740382,  0.28762889,  0.30316414,  0.56241145,  0.38183613,
          0.36788754],
        [ 0.09180836, -0.34740103, -0.42558014, -0.07247998,  0.79887893,
         -0.21518457],
        [-0.23552512, -0.58160029,  0.26026729,  0.64794658, -0.11581137,
         -0.32447329],
        [ 0.19758302,  0.38491308, 

In [92]:
from sklearn.utils.extmath import randomized_svd

In [96]:
mat3_rsvd = randomized_svd(mat3.values, n_components=min(mat3.shape))

/Users/milessmith/Library/Caches/pypoetry/virtualenvs/pyplier-JrjK94hZ-py3.8/lib/python3.8/site-packages/sklearn/utils/extmath.py:368: FutureWarning: If 'random_state' is not supplied, the current default is to use 0 as a fixed seed. This will change to  None in version 1.2 leading to non-deterministic results that better reflect nature of the randomized_svd solver. If you want to silence this warning, set 'random_state' to an integer seed or to None explicitly depending if you want your code to be deterministic or not.
  warnings.warn(


In [97]:
mat3_rsvd

(array([[-0.14411704,  0.61701678,  0.28221381,  0.53776098, -0.34937657,
          0.32806261],
        [ 0.83149661, -0.01776281,  0.22807868,  0.37114008,  0.0633739 ,
         -0.33840327],
        [-0.01145209, -0.35357981,  0.80611018, -0.14618208,  0.1905599 ,
          0.40908956],
        [-0.4741066 , -0.17193955,  0.08526058,  0.58265414,  0.51714712,
         -0.36257878],
        [-0.03115491,  0.66340457,  0.28083572, -0.44505531,  0.4138772 ,
         -0.33269578],
        [ 0.24892734,  0.15584373, -0.36384582,  0.1189071 ,  0.63156251,
          0.60692176]]),
 array([4.28716297, 3.8044636 , 2.31661887, 1.30233026, 1.15503533,
        0.39911119]),
 array([[ 0.47740382,  0.28762889,  0.30316414,  0.56241145,  0.38183613,
          0.36788754],
        [ 0.09180836, -0.34740103, -0.42558014, -0.07247998,  0.79887893,
         -0.21518457],
        [-0.23552512, -0.58160029,  0.26026729,  0.64794658, -0.11581137,
         -0.32447329],
        [ 0.19758302,  0.38491308, 

In [103]:
mat3

V1        V2        V3        V4        V5        V6
1 -0.408441 -0.882143 -1.406640  0.261968  1.529155 -1.288191
2  1.711693  0.849008  0.874837  2.565819  1.069816  1.050955
3 -0.428506 -0.746334  1.254270  1.121962 -1.296201 -0.397341
4 -0.457917 -0.491485 -0.820537 -0.747517 -1.734600 -0.927167
5  0.273810 -1.771688 -0.629742 -0.157095  1.869177 -0.514145
6  1.410448  0.414870 -0.099260 -0.124593  0.758561  0.231126

In [108]:
isinstance(mat3, pd.DataFrame)

True

In [109]:
rng = np.random.default_rng()

In [125]:
rng.shuffle(mat3.values)

In [127]:
mat3

V1        V2        V3        V4        V5        V6
1  1.069816  0.849008  1.711693  1.050955  2.565819  0.874837
2 -1.296201 -0.746334 -0.428506 -0.397341  1.121962  1.254270
3  1.869177 -1.771688  0.273810 -0.514145 -0.157095 -0.629742
4  1.529155 -0.882143 -0.408441 -1.288191  0.261968 -1.406640
5 -1.734600 -0.491485 -0.457917 -0.927167 -0.747517 -0.820537
6  0.758561  0.414870  1.410448  0.231126 -0.124593 -0.099260

In [130]:
rng.shuffle(mat3.values, axis=)
mat3

V1        V2        V3        V4        V5        V6
1  1.529155 -0.882143 -0.408441 -1.288191  0.261968 -1.406640
2 -1.734600 -0.491485 -0.457917 -0.927167 -0.747517 -0.820537
3  1.869177 -1.771688  0.273810 -0.514145 -0.157095 -0.629742
4  0.758561  0.414870  1.410448  0.231126 -0.124593 -0.099260
5  1.069816  0.849008  1.711693  1.050955  2.565819  0.874837
6 -1.296201 -0.746334 -0.428506 -0.397341  1.121962  1.254270

In [131]:
arr = np.arange(9).reshape((3, 3))

In [132]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
rng.shuffle(arr, axis=1)
rng.shuffle(arr, axis=0)
arr

array([[4, 3, 5],
       [7, 6, 8],
       [1, 0, 2]])

In [155]:
arr2 = rng.permuted(arr)
arr2

array([[6, 2, 3],
       [0, 4, 8],
       [1, 5, 7]])

In [157]:
np.copy(arr)

array([[4, 3, 5],
       [7, 6, 8],
       [1, 0, 2]])

In [159]:
from sklearn.utils import shuffle

In [169]:
shuffle(arr, n_samples=3)

array([[7, 6, 8],
       [4, 3, 5],
       [1, 0, 2]])

In [170]:
from itertools import repeat 

In [174]:
repeat(rng.permuted(arr2,out=arr2), 10)

repeat(array([[3, 7, 8],
       [4, 0, 1],
       [5, 2, 6]]), 10)

In [175]:
from itertools import starmap
def repeatfunc(func, times=None, *args):
    """Repeat calls to func with specified arguments.

    Example:  repeatfunc(random.random)
    """
    if times is None:
        return starmap(func, repeat(args))
    return starmap(func, repeat(args, times))

In [182]:
repeatfunc(rng.permuted(arr2,out=arr2), times=10)

In [183]:
arr2 = np.array([-0.4084414,1.7116934, -0.4285055, -0.4579172,  0.2738100, 1.4104480])

In [186]:
abs(np.diff(np.diff(arr2)))

array([4.2603337, 2.1107872, 0.7611389, 0.4049108])

In [192]:
kernel_size = 10
kernel = np.ones(kernel_size) / kernel_size
np.convolve(arr2, kernel, mode='same')

array([0.08747465, 0.04168293, 0.06906393, 0.21010873, 0.21010873,
       0.21010873, 0.21010873, 0.21010873, 0.25095287, 0.07978353])

In [195]:
arr3 = ([
    1.089300602, -1.026029511, 1.465306935, -0.645124236, 0.097941865, 0.114350582, -0.385336619, 0.857331616, -1.373976326,
    0.157552108, 0.951025769, -0.658906624, 0.537273928, 0.493029130, -1.776564824, -0.516410712, -0.471376448, 1.177162764,
    -0.560719344, 1.000541605, -1.279877713, 0.002116907, -0.142827253, 1.802500646, -0.337374057, 0.310118602, 0.098316149,
    1.268375087, 2.104389929, -0.943104103, 0.665192982, 1.805599356, -0.292926603, -0.284755209, -0.155039708, -0.682685066,
    -1.211252184, -1.322234851, 0.319004650, 0.235884941, -0.891136174, 0.452235324, 1.122572825, 0.141235484, 0.762169524,
    0.783130798
])

In [206]:
from scipy.signal.windows import tukey

In [225]:
np.median([arr3[-1],arr3[0],arr3[1]])

0.783130798

In [231]:
def smooth(mat, width=3):
    new_list = list()
    for i, x in enumerate(mat):
        if i == 0:
            new_list.append(np.median([mat[-1],mat[0],mat[1]]))
        else:
            new_list.append(np.median(mat[i-1:i+1]))
    return new_list

In [232]:
smooth(arr3)

[0.783130798,
 0.03163554550000003,
 0.21963871200000007,
 0.41009134950000004,
 -0.2735911855,
 0.1061462235,
 -0.1354930185,
 0.23599749849999999,
 -0.258322355,
 -0.608212109,
 0.5542889385,
 0.1460595725,
 -0.06081634800000002,
 0.5151515289999999,
 -0.641767847,
 -1.146487768,
 -0.49389358,
 0.352893158,
 0.30822171,
 0.2199111305,
 -0.13966805400000004,
 -0.638880403,
 -0.070355173,
 0.8298366964999999,
 0.7325632945,
 -0.013627727499999992,
 0.20421737550000002,
 0.6833456179999999,
 1.686382508,
 0.5806429129999999,
 -0.13895556050000002,
 1.235396169,
 0.7563363765000001,
 -0.288840906,
 -0.2198974585,
 -0.418862387,
 -0.946968625,
 -1.2667435175,
 -0.5016151005,
 0.2774447955,
 -0.3276256165,
 -0.219450425,
 0.7874040744999999,
 0.6319041545,
 0.451702504,
 0.7726501610000001]

In [239]:
from scipy.signal import medfilt

In [242]:
medfilt(arr3, kernel_size=3)

array([ 0.        ,  1.0893006 , -0.64512424,  0.09794187,  0.09794187,
        0.09794187,  0.11435058, -0.38533662,  0.15755211,  0.15755211,
        0.15755211,  0.53727393,  0.49302913,  0.49302913, -0.51641071,
       -0.51641071, -0.47137645, -0.47137645,  1.00054161, -0.56071934,
        0.00211691, -0.14282725,  0.00211691, -0.14282725,  0.3101186 ,
        0.09831615,  0.3101186 ,  1.26837509,  1.26837509,  0.66519298,
        0.66519298,  0.66519298, -0.28475521, -0.28475521, -0.28475521,
       -0.68268507, -1.21125218, -1.21125218,  0.23588494,  0.23588494,
        0.23588494,  0.45223532,  0.45223532,  0.76216952,  0.76216952,
        0.76216952])

In [261]:
?medfilt

Signature: medfilt(volume, kernel_size=None)
Docstring:
Perform a median filter on an N-dimensional array.

Apply a median filter to the input array using a local window-size
given by `kernel_size`. The array will automatically be zero-padded.

Parameters
----------
volume : array_like
    An N-dimensional input array.
kernel_size : array_like, optional
    A scalar or an N-length list giving the size of the median filter
    window in each dimension.  Elements of `kernel_size` should be odd.
    If `kernel_size` is a scalar, then this scalar is used as the size in
    each dimension. Default size is 3 for each dimension.

Returns
-------
out : ndarray
    An array the same size as input containing the median filtered
    result.

Warns
-----
UserWarning
    If array size is smaller than kernel size along any dimension

See Also
--------
scipy.ndimage.median_filter
scipy.signal.medfilt2d

Notes
-----
The more general function `scipy.ndimage.median_filter` has a more
efficient implement

In [244]:
from scipy.ndimage import median_filter

In [260]:
median_filter(arr3, size=3, mode="nearest")

array([ 1.0893006 ,  1.0893006 , -0.64512424,  0.09794187,  0.09794187,
        0.09794187,  0.11435058, -0.38533662,  0.15755211,  0.15755211,
        0.15755211,  0.53727393,  0.49302913,  0.49302913, -0.51641071,
       -0.51641071, -0.47137645, -0.47137645,  1.00054161, -0.56071934,
        0.00211691, -0.14282725,  0.00211691, -0.14282725,  0.3101186 ,
        0.09831615,  0.3101186 ,  1.26837509,  1.26837509,  0.66519298,
        0.66519298,  0.66519298, -0.28475521, -0.28475521, -0.28475521,
       -0.68268507, -1.21125218, -1.21125218,  0.23588494,  0.23588494,
        0.23588494,  0.45223532,  0.45223532,  0.76216952,  0.76216952,
        0.7831308 ])

In [254]:
?median_filter

Signature:
median_filter(
    input,
    size=None,
    footprint=None,
    output=None,
    mode='reflect',
    cval=0.0,
    origin=0,
)
Docstring:
Calculate a multidimensional median filter.

Parameters
----------
input : array_like
    The input array.
size : scalar or tuple, optional
    See footprint, below. Ignored if footprint is given.
footprint : array, optional
    Either `size` or `footprint` must be defined. `size` gives
    the shape that is taken from the input array, at every element
    position, to define the input to the filter function.
    `footprint` is a boolean array that specifies (implicitly) a
    shape, but also which of the elements within this shape will get
    passed to the filter function. Thus ``size=(n,m)`` is equivalent
    to ``footprint=np.ones((n,m))``.  We adjust `size` to the number
    of dimensions of the input array, so that, if the input array is
    shape (10,10,10), and `size` is 2, then the actual size used is
    (2,2,2). When `footprint

In [263]:
arr2

array([-0.4084414,  1.7116934, -0.4285055, -0.4579172,  0.27381  ,
        1.410448 ])

In [269]:
def mutateList(x):
    for i,j in enumerate(x):
        x[i] += 1
    return True

In [270]:
larr = list(arr2)
mutateList(larr)

True

In [271]:
list(arr2)

[-0.4084414, 1.7116934, -0.4285055, -0.4579172, 0.27381, 1.410448]

In [272]:
larr

[0.5915585999999999,
 2.7116933999999997,
 0.5714945,
 0.5420828,
 1.27381,
 2.4104479999999997]