R code:
```
pinv_ridge <- function(m, alfa = 0) {
  msvd = svd(m)
  if (length(msvd$d) == 0) {
    return(array(0, dim(m)[2:1]))
  }
  else {
    if (alpha > 0) {
      ss = (msvd$d^2) + alpha^2
      msvd$d = ss/msvd$d
    }
    out = msvd$v %*% (1/msvd$d * t(msvd$u))
    rownames(out) = rownames(m)
    colnames(out) = colnames(m)
    out
  }
}
```

In [101]:
import numpy as np
import pandas as pd

def pinv_ridge(m: pd.DataFrame, alpha: int = 0) -> pd.DataFrame:
    u, d, v = np.linalg.svd(m)
    if len(d) == 0:
        return np.zeros(tuple(reversed(m.shape)))
    else:
        if (alpha > 0):
            ss = (d**2) + alpha**2
            d = ss/d
        out = v.transpose() @ (1/d * u.transpose())
        out = pd.DataFrame(out)
        if isinstance(m, pd.DataFrame):
            out.index = m.index
            out.columns = m.columns
        return out

In [3]:
mat = pd.read_csv("/home/milo/workspace/pyplier/tests/data/pinv_ridge/randmat.txt", index_col=0)

In [11]:
mat

V1        V2        V3        V4        V5        V6
1 -2.298087 -0.988342 -0.474294 -1.290515  0.852371  1.279294
2 -0.018520 -0.327940 -1.260884 -0.951168  0.818301  1.123552
3  1.140406 -1.323625 -0.453034  0.769536 -0.708671 -0.789409
4 -2.649204  0.625775 -0.218951 -1.597433 -1.229547  1.298778
5 -1.806553 -1.181970 -0.290251  0.010728  0.046671  0.448334
6  1.105622  1.535085  0.029233 -0.788889  0.107858 -0.253067

In [4]:
mat.shape

(6, 6)

In [12]:
pinv_ridge(mat)

V1        V2        V3        V4        V5        V6
1 -0.054047 -0.154853  0.002596 -0.453375 -1.027775 -1.062298
2  0.021699 -0.034325 -0.329383  0.106957 -0.796297  2.327633
3 -0.025941 -0.031689 -0.228774  0.241426  0.152327 -3.535283
4  0.102473 -0.274519  0.061486  0.131167  0.356518  0.045444
5 -0.017784  0.000565  0.189687  0.430845 -1.335506 -0.299667
6  0.149791  0.131477 -0.010510 -0.175850 -0.631556 -1.399395

In [13]:
u, d, v = np.linalg.svd(mat.values)

In [14]:
d

array([5.17646744, 2.90118147, 2.23211297, 1.40161285, 0.49855883,
       0.21772726])

In [16]:
alpha = 0

In [ ]:
if (alpha > 0):
        ss = (d**2) + alpha**2
        d = ss/d
    out = v @ (1/d * u.transpose())
    out = pd.DataFrame(out)
    out.index = m.index
    out.columns = m.columns

In [19]:
1/d

array([0.19318194, 0.34468716, 0.448006  , 0.71346378, 2.00578134,
       4.59290224])

In [20]:
u.transpose()

array([[-0.59312638, -0.20874898,  0.26117546, -0.62324238, -0.34741214,
         0.16518499],
       [ 0.20688972,  0.01013896,  0.4942866 , -0.39409518,  0.42857903,
        -0.61137846],
       [-0.32271349, -0.77576211,  0.08385693,  0.4539906 ,  0.15110788,
        -0.24098986],
       [ 0.24042189, -0.40438685, -0.71911907, -0.48582216,  0.10710431,
        -0.11849835],
       [ 0.59439642, -0.42997585,  0.40140724, -0.08415002, -0.0470438 ,
         0.53980696],
       [-0.30023986,  0.07814259, -0.04664917, -0.08394083,  0.81185391,
         0.48520179]])

In [21]:
(1/d * u.transpose())

array([[-0.1145813 , -0.07195309,  0.11700817, -0.44466086, -0.6968328 ,
         0.75867849],
       [ 0.03996736,  0.00349477,  0.22144336, -0.28117263,  0.85963582,
        -2.80800148],
       [-0.06234242, -0.26739524,  0.03756841,  0.32390585,  0.30308936,
        -1.10684286],
       [ 0.04644517, -0.13938695, -0.32216966, -0.34661651,  0.21482782,
        -0.54425131],
       [ 0.11482665, -0.14820715,  0.17983285, -0.06003799, -0.09435958,
         2.47928059],
       [-0.05800092,  0.02693475, -0.02089911, -0.05988874,  1.62840143,
         2.2284844 ]])

In [22]:
v

array([[ 0.79709079,  0.11265683,  0.12910885,  0.39148824, -0.01807464,
        -0.426258  ],
       [-0.10965073, -0.88024598, -0.13471068,  0.42058098,  0.09409126,
        -0.09620419],
       [-0.39895844,  0.08866534,  0.4224299 ,  0.30706021, -0.69281831,
        -0.28326741],
       [-0.2872199 ,  0.16718265,  0.56610484,  0.27945161,  0.69434008,
        -0.09422662],
       [ 0.00901858, -0.29320191,  0.25320866, -0.68423072,  0.05982164,
        -0.61488729],
       [-0.33298431,  0.30115862, -0.63415109,  0.17116587,  0.15854389,
        -0.58467376]])

In [32]:
np.multiply(v, (1/d * u.transpose()))

array([[-9.13317000e-02, -8.10600746e-03,  1.51067909e-02,
        -1.74079498e-01,  1.25950029e-02, -3.23392779e-01],
       [-4.38244959e-03, -3.07625780e-03, -2.98307859e-02,
        -1.18255862e-01,  8.08842152e-02,  2.70141517e-01],
       [ 2.48720330e-02, -2.37086907e-02,  1.58700191e-02,
         9.94585980e-02, -2.09985860e-01,  3.13532510e-01],
       [-1.33399755e-02, -2.33030811e-02, -1.82381803e-01,
        -9.68625424e-02,  1.49163563e-01,  5.12829599e-02],
       [ 1.03557279e-03,  4.34546200e-02,  4.55352364e-02,
         4.10798366e-02, -5.64474470e-03, -1.52447812e+00],
       [ 1.93133955e-02,  8.11163091e-03,  1.32531928e-02,
        -1.02509088e-02,  2.58173095e-01, -1.30293636e+00]])

In [33]:
v @ (1/d * u.transpose())

array([[-5.40474218e-02, -1.54853242e-01,  2.59602686e-03,
        -4.53375051e-01, -1.02777470e+00, -1.06229752e+00],
       [ 2.16990764e-02, -3.43252890e-02, -3.29382672e-01,
         1.06957075e-01, -7.96297084e-01,  2.32763325e+00],
       [-2.59411778e-02, -3.16888773e-02, -2.28773966e-01,
         2.41426260e-01,  1.52327297e-01, -3.53528303e+00],
       [ 1.02472686e-01, -2.74519158e-01,  6.14856519e-02,
         1.31166720e-01,  3.56518385e-01,  4.54436229e-02],
       [-1.77835685e-02,  5.64629668e-04,  1.89687146e-01,
         4.30844834e-01, -1.33550633e+00, -2.99667233e-01],
       [ 1.49791306e-01,  1.31477045e-01, -1.05102450e-02,
        -1.75849914e-01, -6.31555858e-01, -1.39939512e+00]])

In [52]:
a = v
b = (1/d) * u.transpose()

In [53]:
a

array([[ 0.79709079,  0.11265683,  0.12910885,  0.39148824, -0.01807464,
        -0.426258  ],
       [-0.10965073, -0.88024598, -0.13471068,  0.42058098,  0.09409126,
        -0.09620419],
       [-0.39895844,  0.08866534,  0.4224299 ,  0.30706021, -0.69281831,
        -0.28326741],
       [-0.2872199 ,  0.16718265,  0.56610484,  0.27945161,  0.69434008,
        -0.09422662],
       [ 0.00901858, -0.29320191,  0.25320866, -0.68423072,  0.05982164,
        -0.61488729],
       [-0.33298431,  0.30115862, -0.63415109,  0.17116587,  0.15854389,
        -0.58467376]])

In [54]:
b

array([[-0.1145813 , -0.07195309,  0.11700817, -0.44466086, -0.6968328 ,
         0.75867849],
       [ 0.03996736,  0.00349477,  0.22144336, -0.28117263,  0.85963582,
        -2.80800148],
       [-0.06234242, -0.26739524,  0.03756841,  0.32390585,  0.30308936,
        -1.10684286],
       [ 0.04644517, -0.13938695, -0.32216966, -0.34661651,  0.21482782,
        -0.54425131],
       [ 0.11482665, -0.14820715,  0.17983285, -0.06003799, -0.09435958,
         2.47928059],
       [-0.05800092,  0.02693475, -0.02089911, -0.05988874,  1.62840143,
         2.2284844 ]])

In [62]:
A = np.array([[1,5,1], [3,8,3], [4,9,3]])
B = np.array([[2,8,3],[4,9,4],[5,2,5]])

In [63]:
A

array([[1, 5, 1],
       [3, 8, 3],
       [4, 9, 3]])

In [64]:
B

array([[2, 8, 3],
       [4, 9, 4],
       [5, 2, 5]])

In [66]:
A @ B

array([[ 27,  55,  28],
       [ 53, 102,  56],
       [ 59, 119,  63]])

In [67]:
np.multiply(A,B,)

array([[ 2, 40,  3],
       [12, 72, 12],
       [20, 18, 15]])

In [89]:
a

array([[ 0.79709079,  0.11265683,  0.12910885,  0.39148824, -0.01807464,
        -0.426258  ],
       [-0.10965073, -0.88024598, -0.13471068,  0.42058098,  0.09409126,
        -0.09620419],
       [-0.39895844,  0.08866534,  0.4224299 ,  0.30706021, -0.69281831,
        -0.28326741],
       [-0.2872199 ,  0.16718265,  0.56610484,  0.27945161,  0.69434008,
        -0.09422662],
       [ 0.00901858, -0.29320191,  0.25320866, -0.68423072,  0.05982164,
        -0.61488729],
       [-0.33298431,  0.30115862, -0.63415109,  0.17116587,  0.15854389,
        -0.58467376]])

In [87]:
pd.DataFrame(a).to_csv("mata.csv")

In [90]:
b

array([[-0.1145813 , -0.07195309,  0.11700817, -0.44466086, -0.6968328 ,
         0.75867849],
       [ 0.03996736,  0.00349477,  0.22144336, -0.28117263,  0.85963582,
        -2.80800148],
       [-0.06234242, -0.26739524,  0.03756841,  0.32390585,  0.30308936,
        -1.10684286],
       [ 0.04644517, -0.13938695, -0.32216966, -0.34661651,  0.21482782,
        -0.54425131],
       [ 0.11482665, -0.14820715,  0.17983285, -0.06003799, -0.09435958,
         2.47928059],
       [-0.05800092,  0.02693475, -0.02089911, -0.05988874,  1.62840143,
         2.2284844 ]])

In [88]:
pd.DataFrame(b).to_csv("matb.csv")

In [83]:
pd.DataFrame(a.astype(np.float64) @ b.astype(np.float64))

0         1         2         3         4         5
0 -0.054047 -0.154853  0.002596 -0.453375 -1.027775 -1.062298
1  0.021699 -0.034325 -0.329383  0.106957 -0.796297  2.327633
2 -0.025941 -0.031689 -0.228774  0.241426  0.152327 -3.535283
3  0.102473 -0.274519  0.061486  0.131167  0.356518  0.045444
4 -0.017784  0.000565  0.189687  0.430845 -1.335506 -0.299667
5  0.149791  0.131477 -0.010510 -0.175850 -0.631556 -1.399395

In [80]:
mat1 = np.array([[1, 2, 3],
                 [3, 4, 5],
                 [7, 6, 4]])
mat2 = np.array([[5, 2, 6],
                 [5, 6, 7],
                 [7, 6, 4]])

In [85]:
np.dot(mat1,mat2)

array([[ 36,  32,  32],
       [ 70,  60,  66],
       [ 93,  74, 100]])

In [86]:
np.dot(a,b)

array([[-5.40474218e-02, -1.54853242e-01,  2.59602686e-03,
        -4.53375051e-01, -1.02777470e+00, -1.06229752e+00],
       [ 2.16990764e-02, -3.43252890e-02, -3.29382672e-01,
         1.06957075e-01, -7.96297084e-01,  2.32763325e+00],
       [-2.59411778e-02, -3.16888773e-02, -2.28773966e-01,
         2.41426260e-01,  1.52327297e-01, -3.53528303e+00],
       [ 1.02472686e-01, -2.74519158e-01,  6.14856519e-02,
         1.31166720e-01,  3.56518385e-01,  4.54436229e-02],
       [-1.77835685e-02,  5.64629668e-04,  1.89687146e-01,
         4.30844834e-01, -1.33550633e+00, -2.99667233e-01],
       [ 1.49791306e-01,  1.31477045e-01, -1.05102450e-02,
        -1.75849914e-01, -6.31555858e-01, -1.39939512e+00]])

In [96]:
a

array([[ 0.79709079,  0.11265683,  0.12910885,  0.39148824, -0.01807464,
        -0.426258  ],
       [-0.10965073, -0.88024598, -0.13471068,  0.42058098,  0.09409126,
        -0.09620419],
       [-0.39895844,  0.08866534,  0.4224299 ,  0.30706021, -0.69281831,
        -0.28326741],
       [-0.2872199 ,  0.16718265,  0.56610484,  0.27945161,  0.69434008,
        -0.09422662],
       [ 0.00901858, -0.29320191,  0.25320866, -0.68423072,  0.05982164,
        -0.61488729],
       [-0.33298431,  0.30115862, -0.63415109,  0.17116587,  0.15854389,
        -0.58467376]])

In [103]:
pinv_ridge(a).to_csv("/home/milo/workspace/pyplier/tests/data/pinv_ridge/expected_result.csv")

In [100]:
pd.DataFrame(v)

0         1         2         3         4         5
0  0.797091  0.112657  0.129109  0.391488 -0.018075 -0.426258
1 -0.109651 -0.880246 -0.134711  0.420581  0.094091 -0.096204
2 -0.398958  0.088665  0.422430  0.307060 -0.692818 -0.283267
3 -0.287220  0.167183  0.566105  0.279452  0.694340 -0.094227
4  0.009019 -0.293202  0.253209 -0.684231  0.059822 -0.614887
5 -0.332984  0.301159 -0.634151  0.171166  0.158544 -0.584674

In [99]:
pd.DataFrame(u)

0         1         2         3         4         5
0 -0.593126  0.206890 -0.322713  0.240422  0.594396 -0.300240
1 -0.208749  0.010139 -0.775762 -0.404387 -0.429976  0.078143
2  0.261175  0.494287  0.083857 -0.719119  0.401407 -0.046649
3 -0.623242 -0.394095  0.453991 -0.485822 -0.084150 -0.083941
4 -0.347412  0.428579  0.151108  0.107104 -0.047044  0.811854
5  0.165185 -0.611378 -0.240990 -0.118498  0.539807  0.485202