In [1]:
import numpy as np

In [2]:
arr = np.random.rand(10, 6)

In [3]:
arr

array([[0.60183502, 0.0809301 , 0.12289166, 0.32911331, 0.29105952,
        0.05242704],
       [0.9750604 , 0.21979789, 0.41908536, 0.1810258 , 0.22429196,
        0.57608637],
       [0.0496156 , 0.67388523, 0.04142534, 0.79776934, 0.10481725,
        0.69585739],
       [0.52922822, 0.21103553, 0.43127104, 0.92288849, 0.30677605,
        0.53745723],
       [0.57503091, 0.60458365, 0.20298634, 0.07961709, 0.39388301,
        0.7537117 ],
       [0.51378038, 0.01925013, 0.31976996, 0.07806788, 0.06719728,
        0.88021687],
       [0.53623354, 0.41702569, 0.2230367 , 0.49073616, 0.67388402,
        0.47980481],
       [0.67353466, 0.78974883, 0.29231957, 0.48303029, 0.55829753,
        0.68301835],
       [0.17020147, 0.2669902 , 0.45293863, 0.42886656, 0.87689911,
        0.36486131],
       [0.6083839 , 0.1594514 , 0.27002049, 0.29536163, 0.13329498,
        0.33486165]])

In [17]:
np.apply_along_axis(lambda x: ((x - np.mean(x)) / np.std(x, ddof=1)), 1, arr)

array([[ 1.71246298, -0.79705463, -0.59490013,  0.39859573,  0.21526734,
        -0.93437129],
       [ 1.77512065, -0.69617162, -0.04408368, -0.82303766, -0.68146658,
         0.46963889],
       [-0.94830266,  0.77122081, -0.97086239,  1.11245417, -0.79625211,
         0.83174217],
       [ 0.15946939, -1.1266969 , -0.2364832 ,  1.75068311, -0.73970425,
         0.19273187],
       [ 0.54374108,  0.65846904, -0.90058882, -1.37952581, -0.15950082,
         1.23740533],
       [ 0.59767754, -0.87477186,  0.02001716, -0.69964373, -0.73201063,
         1.68873152],
       [ 0.44517265, -0.35751007, -1.66372954,  0.13881731,  1.37203831,
         0.06521134],
       [ 0.52960019,  1.18755399, -1.62867278, -0.54895216, -0.12282199,
         0.58329274],
       [-1.05016737, -0.65403422,  0.1070083 ,  0.00848708,  1.84217733,
        -0.25347113],
       [ 1.81091959, -0.82730126, -0.17752499, -0.02860388, -0.98101352,
         0.20352405]])

In [9]:
arr[0, :]

array([0.60183502, 0.0809301 , 0.12289166, 0.32911331, 0.29105952,
       0.05242704])

In [16]:
a = arr[0, :]
((a - np.mean(a)) / np.std(a, ddof=1))

array([ 1.71246298, -0.79705463, -0.59490013,  0.39859573,  0.21526734,
       -0.93437129])

In [15]:
np.std(a, ddof=1)

0.20757173409409946

In [13]:
np.mean(a)

0.24637610824871684

In [18]:
((arr - np.mean(arr)) / np.std(arr, ddof=1))

array([[ 0.76219515, -1.29432677, -1.12866339, -0.31450453, -0.46474011,
        -1.40685625],
       [ 2.23568129, -0.74607958,  0.04070325, -0.89915098, -0.72833708,
         0.66054002],
       [-1.41795575,  1.04664791, -1.45029075,  1.53573981, -1.20002076,
         1.13339355],
       [ 0.475545  , -0.78067319,  0.08881208,  2.02970766, -0.40269158,
         0.50803297],
       [ 0.65637306,  0.7730467 , -0.81245122, -1.29951049, -0.05879511,
         1.36180116],
       [ 0.41455724, -1.53783799, -0.35139192, -1.30562673, -1.34854365,
         1.86124096],
       [ 0.50320187,  0.03257174, -0.73329281,  0.32357914,  1.04664313,
         0.28042238],
       [ 1.04526384,  1.50407502, -0.45976548,  0.29315652,  0.59031003,
         1.08270529],
       [-0.94188521, -0.55976531,  0.17435526,  0.07931923,  1.84814254,
        -0.17337217],
       [ 0.78805   , -0.98432627, -0.54780177, -0.44775547, -1.0875913 ,
        -0.29181021]])

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame(arr)

In [22]:
df.apply(lambda x: ((x - np.mean(x)) / np.std(x, ddof=1)), axis=1)

0         1         2         3         4         5
0  1.712463 -0.797055 -0.594900  0.398596  0.215267 -0.934371
1  1.775121 -0.696172 -0.044084 -0.823038 -0.681467  0.469639
2 -0.948303  0.771221 -0.970862  1.112454 -0.796252  0.831742
3  0.159469 -1.126697 -0.236483  1.750683 -0.739704  0.192732
4  0.543741  0.658469 -0.900589 -1.379526 -0.159501  1.237405
5  0.597678 -0.874772  0.020017 -0.699644 -0.732011  1.688732
6  0.445173 -0.357510 -1.663730  0.138817  1.372038  0.065211
7  0.529600  1.187554 -1.628673 -0.548952 -0.122822  0.583293
8 -1.050167 -0.654034  0.107008  0.008487  1.842177 -0.253471
9  1.810920 -0.827301 -0.177525 -0.028604 -0.981014  0.203524