In [16]:
import numpy as np
from typing import Union


def colSumNorm(mat: np.ndarray, return_all: bool = False) -> Union[np.ndarray, dict[str, np.ndarray]]:
    ss = np.sqrt(np.sum(np.power(mat, 2), axis=1))
    ss = np.where(ss < 1e-16, 1, ss)
    if return_all:
        return {"mat": (mat.transpose() / ss).transpose(), "ss": ss}
    else:
        return (mat.transpose() / ss).transpose()

In [2]:
from numpy.random import default_rng

In [3]:
rng = default_rng()

In [4]:
arr = rng.standard_normal((10, 10))

In [5]:
np.savetxt("/Users/milessmith/workspace/pyplier/tests/data/colSumNorm/test_arr.csv.gz", arr, delimiter=",")

In [17]:
arr

array([[ 1.7398792 , -0.29240654, -0.42338046, -0.09782688,  0.95653223,
         0.63152777, -0.64358388,  0.10471505,  1.05548429,  0.7771689 ],
       [ 0.15949798, -0.80522591,  1.49111024,  0.36379771, -0.30550267,
         0.4035162 ,  1.25413517, -0.07374653, -0.01119639, -1.76488928],
       [-0.80473435,  0.57432585, -0.76473834,  0.45488463,  1.20344701,
         1.09148407,  1.83068494, -0.36914   , -0.62651351,  0.80907749],
       [ 0.24198343,  0.49295325,  1.12314114, -0.09668591,  1.55930758,
        -0.24091035,  1.82139166, -0.74094965,  1.76506537, -1.34010124],
       [-0.23988207, -0.54551783, -1.40393288,  0.6419897 ,  0.51554414,
        -1.65390987, -0.23983811,  1.42100628, -0.08810647,  0.50339505],
       [-1.04049836,  0.63037021,  0.50404195,  1.05804532, -0.01340408,
         0.6216234 ,  0.26322809,  1.59805955,  0.04697477,  0.92805632],
       [ 0.76960692, -1.46496327,  0.89420536, -1.56428001, -2.00814285,
         0.24732044, -1.18491478,  0.56206235

In [22]:
arr2 = np.loadtxt("/Users/milessmith/workspace/pyplier/tests/data/colSumNorm/test_arr.csv.gz",delimiter=",")

In [23]:
arr2

array([[ 1.7398792 , -0.29240654, -0.42338046, -0.09782688,  0.95653223,
         0.63152777, -0.64358388,  0.10471505,  1.05548429,  0.7771689 ],
       [ 0.15949798, -0.80522591,  1.49111024,  0.36379771, -0.30550267,
         0.4035162 ,  1.25413517, -0.07374653, -0.01119639, -1.76488928],
       [-0.80473435,  0.57432585, -0.76473834,  0.45488463,  1.20344701,
         1.09148407,  1.83068494, -0.36914   , -0.62651351,  0.80907749],
       [ 0.24198343,  0.49295325,  1.12314114, -0.09668591,  1.55930758,
        -0.24091035,  1.82139166, -0.74094965,  1.76506537, -1.34010124],
       [-0.23988207, -0.54551783, -1.40393288,  0.6419897 ,  0.51554414,
        -1.65390987, -0.23983811,  1.42100628, -0.08810647,  0.50339505],
       [-1.04049836,  0.63037021,  0.50404195,  1.05804532, -0.01340408,
         0.6216234 ,  0.26322809,  1.59805955,  0.04697477,  0.92805632],
       [ 0.76960692, -1.46496327,  0.89420536, -1.56428001, -2.00814285,
         0.24732044, -1.18491478,  0.56206235

In [25]:
np.array_equal(arr, arr2)

True

In [26]:
res = colSumNorm(arr, return_all=True)
res

{'mat': array([[ 0.66925918, -0.11247664, -0.16285686, -0.03762993,  0.36793817,
          0.24292247, -0.24755995,  0.04027953,  0.40600092,  0.29894456],
        [ 0.05646522, -0.28506479,  0.52788047,  0.12879109, -0.10815357,
          0.14285216,  0.44398694, -0.02610763, -0.00396373, -0.62480329],
        [-0.26908908,  0.19204451, -0.25571511,  0.15210546,  0.40241161,
          0.36497316,  0.61214899, -0.12343395, -0.20949515,  0.27054135],
        [ 0.06753196,  0.13757181,  0.31344262, -0.02698279,  0.43516655,
         -0.06723249,  0.50830813, -0.20678185,  0.49258877, -0.37399114],
        [-0.08440346, -0.19194261, -0.49397934,  0.22588662,  0.18139625,
         -0.58193474, -0.08438799,  0.49998669, -0.03100061,  0.17712154],
        [-0.40118115,  0.24304954,  0.19434161,  0.40794667, -0.00516816,
          0.23967706,  0.10149189,  0.61615798,  0.01811189,  0.35782728],
        [ 0.21520468, -0.40964672,  0.25004606, -0.43741859, -0.56153567,
          0.06915805, -0.

In [27]:
np.savetxt("/Users/milessmith/workspace/pyplier/tests/data/colSumNorm/res_ss.csv.gz", res["ss"], delimiter=",")

In [28]:
np.savetxt("/Users/milessmith/workspace/pyplier/tests/data/colSumNorm/res_mat.csv.gz", res["mat"], delimiter=",")

In [19]:
np.sum(arr, axis=1)

array([ 3.80810969,  0.71149652,  3.3987778 ,  4.58519528, -1.08925206,
        4.59649716, -5.07297687, -2.81435254, -2.16214481,  1.62961853])

In [20]:
np.sqrt(np.sum(np.power(arr, 2), axis=0))

array([2.87463599, 2.47600624, 3.01220747, 2.3577199 , 3.39364345,
       2.57313191, 3.63771531, 2.54170025, 2.67402557, 3.06924963])

In [21]:
np.sqrt(np.sum(np.power(arr, 2), axis=1))

array([2.59970914, 2.82471188, 2.99058719, 3.58324323, 2.84208823,
       2.59358737, 3.57616259, 2.94841902, 2.13869331, 2.45908648])

In [33]:
from hypothesis import strategies as st

In [39]:
from hypothesis.extra.numpy import arrays, array_shapes

In [53]:
array_shapes(min_dims=1,min_side=2, max_dims=2)

(4, 4)

In [95]:
arrays(np.float32, array_shapes(min_dims=2,min_side=2, max_dims=2)).example()

array([[    -inf,     -inf,     -inf, -2.00001,     -inf,     -inf],
       [    -inf,     -inf,     -inf, -0.     ,     -inf,     -inf],
       [    -inf,  0.5    ,     -inf,     -inf,     -inf,     -inf],
       [    -inf,     -inf,     -inf,     -inf,     -inf,     -inf],
       [    -inf,     -inf,     -inf,     -inf,     -inf,     -inf],
       [    -inf,     -inf, -0.99999, -2.00001,     -inf,     -inf],
       [    -inf,     -inf,     -inf,     -inf,     -inf,  2.00001]],
      dtype=float32)

In [86]:
arr_rand = arrays(np.float32, array_shapes(min_dims=2,min_side=1, max_dims=2)).example()

In [87]:
arr_rand

array([[           nan, -3.5652418e+16],
       [ 2.2204460e-16,  1.4012985e-45],
       [ 2.2204460e-16, -1.1920929e-07]], dtype=float32)

In [88]:
colSumNorm(arr_rand, return_all=True)

{'mat': array([[           nan,            nan],
        [ 1.0000000e+00,  6.3108872e-30],
        [ 1.8626451e-09, -1.0000000e+00]], dtype=float32),
 'ss': array([          nan, 2.2204460e-16, 1.1920929e-07], dtype=float32)}

In [92]:
colSumNorm(np.array([[0., 0.]]), return_all=True)

{'mat': array([[0., 0.]]), 'ss': array([1.])}

In [97]:
np.power(np.inf, np.inf)

inf