In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import seaborn as sns
from rich import print as rp
from typing import Optional
from pyplier.plier_res import PLIERResults

sns.set_theme()
%matplotlib inline

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
auc_cutoff: float = 0.6
fdr_cutoff: float = 0.05
indexCol: Optional[list[str]] = None
indexRow: Optional[list[str]] = None
top: int = 3
sort_row: bool = False

In [4]:
plierRes = PLIERResults.from_disk(
    "/Users/milessmith/workspace/pyplier/tests/data/common/plierRes.json.gz"
)

In [23]:
plierRes.B.iloc[0,:].mean()

1.2335811384723961e-17

In [25]:
i = 0

In [365]:
Y = pd.read_csv("~/workspace/pyplier/tests/data/common/plierRes_y.csv.gz", index_col=0)
Z = pd.read_csv("~/workspace/pyplier/tests/data/common/plierRes_z.csv.gz", index_col=0)
B = pd.read_csv("~/workspace/pyplier/tests/data/common/plierRes_b.csv.gz", index_col=0)

In [33]:
coef = Z.iloc[:, i]

In [41]:
B.iloc[i,:]

BD8001    0.999463
BD8002    0.042062
BD8003    1.265468
BD8004    2.361500
BD8005   -0.068039
BD8006    0.771152
BD8007   -1.304164
BD8008   -0.670169
BD8009    0.287863
BD8010    1.334602
BD8011   -1.034933
BD8012   -0.234996
BD8013   -0.355119
BD8015   -0.812612
BD8017   -1.303163
BD8018   -1.730652
BD8019   -0.278619
BD8020    0.730356
BD8021   -0.752210
BD8024   -2.530996
BD8025   -0.994928
BD8026    0.437689
BD8027    1.297540
BD8028    0.306322
BD8029    1.023315
BD8030    0.949314
BD8031    1.493796
BD8032   -0.122788
BD8033    1.042694
BD8034    1.000287
BD8038    0.931426
BD8041   -0.101332
BD8042    0.008380
BD8043   -0.497600
BD8044   -0.041143
BD8045   -3.449765
Name: 1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY, dtype: float64

In [ ]:
var_reg = sum((Y.T @ coef - B.iloc[i, :].mean()))**2

In [87]:
B.shape[0]

30

In [88]:
Z.shape[1]

30

In [81]:
Y.transpose() @ coef - B.iloc[i,:].mean()

BD8001     97.612368
BD8002     26.779554
BD8003    122.534238
BD8004    200.002413
BD8005      5.845366
BD8006     83.471334
BD8007   -110.881083
BD8008    -32.884940
BD8009     48.534085
BD8010     66.462627
BD8011   -120.568757
BD8012    -43.520376
BD8013    -19.693951
BD8015    -73.997212
BD8017   -148.630707
BD8018   -173.642002
BD8019      0.457483
BD8020     72.119560
BD8021   -107.009448
BD8024   -211.504502
BD8025   -104.417920
BD8026     54.487651
BD8027    105.238381
BD8028     47.028924
BD8029     75.878440
BD8030     86.388935
BD8031    111.026724
BD8032     14.392624
BD8033     89.039612
BD8034    102.208642
BD8038     66.983837
BD8041     -8.326447
BD8042     -4.472341
BD8043    -55.631024
BD8044    -11.999871
BD8045   -249.312217
dtype: float64

In [101]:
np.subtract((Y.transpose().values @ Z.values), np.mean(B.values, axis=1))

array([[  97.61236777,  -60.20057493,  -10.89520614, ...,  -18.07576662,
          98.13063822,   49.9171736 ],
       [  26.77955362, -100.73714551,  -63.06415212, ...,   26.37459887,
           8.7064486 ,  219.95483562],
       [ 122.53423786,    8.08828833,   60.01898894, ...,  -74.3769909 ,
         173.54613773,  -61.94137168],
       ...,
       [ -55.63102428,  -24.32953188,   82.64948919, ...,    7.79782277,
         -51.18559562,  -70.11413437],
       [ -11.99987098,  -20.43311787,  -25.4702512 , ...,   24.37237729,
         -52.70166344,  134.58683871],
       [-249.31221745,   40.33036223,   18.12621173, ...,   77.61561634,
        -158.325816  ,   14.67818591]])

In [83]:
(Y.T @ coef - B.iloc[i,:].mean()).pow(2).sum()

369594.6876235475

In [102]:
from numpy.linalg import pinv

In [138]:
alpha = np.ones((1,1))

In [139]:
alpha

array([[1.]])

In [137]:
alpha[[1,0]] = 2

/var/folders/h6/9_7l_jld48bgxx9r35h2_7bm0000gn/T/ipykernel_11704/2954598121.py:1: DeprecationWarning: Out of bound index found. This was previously ignored when the indexing result contained no elements. In the future the index error will be raised. This error occurs either due to an empty slice, or if an array has zero elements even before indexing.
(Use `warnings.simplefilter('error')` to turn this DeprecationWarning into an error and get more details on the invalid index.)
  alpha[[1,0]] = 2


In [136]:
alpha

array([], shape=(1, 0), dtype=float64)

In [120]:
pinv(alpha)

array([[0.5]])

In [170]:
pinv([[B.iloc[0,:] @ B.iloc[0,:]]])

array([[0.02030429]])

In [167]:
pinv([[np.dot(B.iloc[0,:], B.iloc[0,:],)]])


array([[0.02030429]])

In [162]:
np.dot(B.iloc[0,:], B.iloc[0,:],)


49.25066570263017

In [166]:
pinv([[50]])

array([[0.02]])

In [164]:
np.dot(B.iloc[0:10,:], B.iloc[:,0:10],)


ValueError: shapes (10,36) and (30,10) not aligned: 36 (dim 1) != 30 (dim 0)

In [175]:
pinv(np.array([[np.dot(B.iloc[0,:], B.iloc[0,:],)]]))


array([[0.02030429]])

In [ ]:
for i in range(k)
      Zreg = Y @ B.iloc[i, ] @ ginv(B.iloc[i, ] @ B.iloc[i, ])
      res = c(res, (Zreg @ B[i, ] - Y.mean().pow(2)).sum())

In [176]:
Y @ B.iloc[i, :] 

GAS6       -22.710032
MMP14       -5.852222
MARCKSL1   -28.820871
SPARC       -8.931645
CTSD       -30.712846
              ...    
CFL2        18.601244
CFL1       -19.631233
SELL        14.864758
GNGT2      -12.868373
SERPINH1   -17.238086
Length: 5892, dtype: float64

In [181]:
pinv([[np.dot(B.iloc[i, :], B.iloc[i, :],)]], )

array([[0.02030429]])

In [190]:
1/np.dot(B.iloc[i, :], B.iloc[i, :],)

0.020304294078741684

In [192]:
Zreg = np.multiply(Y @ B.iloc[i,:], 1/np.dot(B.iloc[i, :], B.iloc[i, :],))
Zreg.head()

GAS6       -0.461111
MMP14      -0.118825
MARCKSL1   -0.585187
SPARC      -0.181351
CTSD       -0.623603
dtype: float64

In [ ]:
sum(Zreg %*% B.iloc[i,:]) - mean(Y))^2))

In [ ]:
sum(
    (
        Zreg %*% B[i, ] - mean(Y)
    )^2
)

In [194]:
Zreg

GAS6       -0.461111
MMP14      -0.118825
MARCKSL1   -0.585187
SPARC      -0.181351
CTSD       -0.623603
              ...   
CFL2        0.377685
CFL1       -0.398598
SELL        0.301818
GNGT2      -0.261283
SERPINH1   -0.350007
Length: 5892, dtype: float64

In [195]:
B.iloc[i,:]

BD8001    0.999463
BD8002    0.042062
BD8003    1.265468
BD8004    2.361500
BD8005   -0.068039
BD8006    0.771152
BD8007   -1.304164
BD8008   -0.670169
BD8009    0.287863
BD8010    1.334602
BD8011   -1.034933
BD8012   -0.234996
BD8013   -0.355119
BD8015   -0.812612
BD8017   -1.303163
BD8018   -1.730652
BD8019   -0.278619
BD8020    0.730356
BD8021   -0.752210
BD8024   -2.530996
BD8025   -0.994928
BD8026    0.437689
BD8027    1.297540
BD8028    0.306322
BD8029    1.023315
BD8030    0.949314
BD8031    1.493796
BD8032   -0.122788
BD8033    1.042694
BD8034    1.000287
BD8038    0.931426
BD8041   -0.101332
BD8042    0.008380
BD8043   -0.497600
BD8044   -0.041143
BD8045   -3.449765
Name: 1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY, dtype: float64

In [198]:
Zreg * B.iloc[i,:].T

A2M      NaN
AAAS     NaN
AANAT    NaN
AARS     NaN
AARS2    NaN
          ..
ZNRD1    NaN
ZW10     NaN
ZWILCH   NaN
ZWINT    NaN
ZYX      NaN
Length: 5928, dtype: float64

In [239]:
res = np.reshape(Zreg.values, (5892,1)) @ np.reshape(B.iloc[i,:].values, (1,B.shape[1]))
res

array([[-0.46086358, -0.01939535, -0.58352131, ...,  0.22944901,
         0.01897165,  1.59072501],
       [-0.11876142, -0.00499805, -0.15036949, ...,  0.05912746,
         0.00488887,  0.40991907],
       [-0.58487322, -0.02461427, -0.74053581, ...,  0.29118938,
         0.02407657,  2.01875891],
       ...,
       [ 0.30165636,  0.01269515,  0.38194147, ..., -0.15018491,
        -0.01241782, -1.04120252],
       [-0.26114294, -0.01099015, -0.3306455 , ...,  0.13001459,
         0.01075007,  0.90136566],
       [-0.34981923, -0.01472207, -0.44292277, ...,  0.17416363,
         0.01440046,  1.20744235]])

In [219]:
Zreg.values @ B.values

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 36 is different from 5892)

In [215]:
pd.DataFrame(res)

0         1         2         3         4         5         6   \
0    -0.460864 -0.019395 -0.583521 -1.088914  0.031374 -0.355587  0.601364   
1    -0.118761 -0.004998 -0.150369 -0.280606  0.008085 -0.091632  0.154968   
2    -0.584873 -0.024614 -0.740536 -1.381920  0.039816 -0.451268  0.763180   
3    -0.181253 -0.007628 -0.229494 -0.428260  0.012339 -0.139849  0.236511   
4    -0.623268 -0.026230 -0.789149 -1.472638  0.042429 -0.480892  0.813280   
...        ...       ...       ...       ...       ...       ...       ...   
5887  0.377482  0.015886  0.477948  0.891904 -0.025697  0.291253 -0.492563   
5888 -0.398384 -0.016766 -0.504413 -0.941290  0.027120 -0.307380  0.519837   
5889  0.301656  0.012695  0.381941  0.712744 -0.020536  0.232748 -0.393621   
5890 -0.261143 -0.010990 -0.330645 -0.617020  0.017778 -0.201489  0.340756   
5891 -0.349819 -0.014722 -0.442923 -0.826542  0.023814 -0.269909  0.456467   

            7         8         9   ...        26        27        28  \
0     0.309022 -0.132737 -0.615400  ... -0.688806  0.056619 -0.480798   
1     0.079633 -0.034205 -0.158584  ... -0.177501  0.014590 -0.123898   
2     0.392174 -0.168454 -0.780992  ... -0.874151  0.071854 -0.610172   
3     0.121536 -0.052204 -0.242031  ... -0.270901  0.022268 -0.189093   
4     0.417919 -0.179512 -0.832261  ... -0.931535  0.076571 -0.650227   
...        ...       ...       ...  ...       ...       ...       ...   
5887 -0.253113  0.108722  0.504059  ...  0.564184 -0.046375  0.393810   
5888  0.267128 -0.114742 -0.531970  ... -0.595425  0.048943 -0.415616   
5889 -0.202269  0.086882  0.402807  ...  0.450855 -0.037060  0.314704   
5890  0.175104 -0.075214 -0.348709  ... -0.390304  0.032082 -0.272439   
5891  0.234564 -0.100754 -0.467120  ... -0.522839  0.042977 -0.364951   

            29        30        31        32        33        34        35  
0    -0.461243 -0.429491  0.046725 -0.003864  0.229449  0.018972  1.590725  
1    -0.118859 -0.110677  0.012041 -0.000996  0.059127  0.004889  0.409919  
2    -0.585355 -0.545059  0.059298 -0.004904  0.291189  0.024077  2.018759  
3    -0.181403 -0.168915  0.018377 -0.001520  0.090240  0.007461  0.625617  
4    -0.623781 -0.580840  0.063191 -0.005226  0.310305  0.025657  2.151282  
...        ...       ...       ...       ...       ...       ...       ...  
5887  0.377793  0.351786 -0.038272  0.003165 -0.187936 -0.015539 -1.302925  
5888 -0.398713 -0.371265  0.040391 -0.003340  0.198343  0.016400  1.375070  
5889  0.301905  0.281122 -0.030584  0.002529 -0.150185 -0.012418 -1.041203  
5890 -0.261358 -0.243366  0.026476 -0.002190  0.130015  0.010750  0.901366  
5891 -0.350108 -0.326006  0.035467 -0.002933  0.174164  0.014400  1.207442  

[5892 rows x 36 columns]

In [225]:
Zreg

GAS6       -0.461111
MMP14      -0.118825
MARCKSL1   -0.585187
SPARC      -0.181351
CTSD       -0.623603
              ...   
CFL2        0.377685
CFL1       -0.398598
SELL        0.301818
GNGT2      -0.261283
SERPINH1   -0.350007
Length: 5892, dtype: float64

In [227]:
B.iloc[0,:].shape

(36,)

In [236]:
len(Zreg)

5892

In [238]:
B.shape[1]

36

In [235]:
np.matmul(
    np.reshape(Zreg.values, (len(Zreg),1)),
    np.reshape(B.iloc[0,:].values, (1,B.shape[1]))
)

array([[-0.46086358, -0.01939535, -0.58352131, ...,  0.22944901,
         0.01897165,  1.59072501],
       [-0.11876142, -0.00499805, -0.15036949, ...,  0.05912746,
         0.00488887,  0.40991907],
       [-0.58487322, -0.02461427, -0.74053581, ...,  0.29118938,
         0.02407657,  2.01875891],
       ...,
       [ 0.30165636,  0.01269515,  0.38194147, ..., -0.15018491,
        -0.01241782, -1.04120252],
       [-0.26114294, -0.01099015, -0.3306455 , ...,  0.13001459,
         0.01075007,  0.90136566],
       [-0.34981923, -0.01472207, -0.44292277, ...,  0.17416363,
         0.01440046,  1.20744235]])

In [230]:
Zreg * B.iloc[0,:]

A2M      NaN
AAAS     NaN
AANAT    NaN
AARS     NaN
AARS2    NaN
          ..
ZNRD1    NaN
ZW10     NaN
ZWILCH   NaN
ZWINT    NaN
ZYX      NaN
Length: 5928, dtype: float64

In [ ]:
# res = c(res, sum((matrix(Zreg, ncol = 1) %*% matrix(B[i, ], nrow = 1) - mean(Y))^2))

In [243]:
Y.mean().mean()

6.437751566402817e-16

In [252]:
np.mean(Y.values.flatten())

6.435495653849009e-16

In [240]:
res

array([[-0.46086358, -0.01939535, -0.58352131, ...,  0.22944901,
         0.01897165,  1.59072501],
       [-0.11876142, -0.00499805, -0.15036949, ...,  0.05912746,
         0.00488887,  0.40991907],
       [-0.58487322, -0.02461427, -0.74053581, ...,  0.29118938,
         0.02407657,  2.01875891],
       ...,
       [ 0.30165636,  0.01269515,  0.38194147, ..., -0.15018491,
        -0.01241782, -1.04120252],
       [-0.26114294, -0.01099015, -0.3306455 , ...,  0.13001459,
         0.01075007,  0.90136566],
       [-0.34981923, -0.01472207, -0.44292277, ...,  0.17416363,
         0.01440046,  1.20744235]])

In [ ]:
res = c(
    res,
    sum(
        (np.reshape(Zreg.values, (5892,1)) @ np.reshape(B.iloc[i,:].values, (1,B.shape[1])) - np.mean(Y.values.flatten()))**2
       )
)

In [256]:
np.sum(((np.reshape(Zreg.values, (5892,1)) @ np.reshape(B.iloc[i,:].values, (1,B.shape[1])) - np.mean(Y.values.flatten()))**2))

48688.813829927574

In [265]:
res2 = [calc_res(B.iloc[i,:].values, Y.values) for i in range(B.shape[0])]

TypeError: unsupported operand type(s) for @: 'numpy.float64' and 'numpy.float64'

In [261]:
res2

[48688.813829927574,
 35385.04648817192,
 28441.355032852527,
 18836.359020244417,
 8226.737247076258,
 13986.197661098797,
 52602.64714125985,
 13904.701663370213,
 10476.55048142907,
 20063.63126424715,
 11004.33192528285,
 48674.78124574433,
 15980.813522146469,
 18083.950262984632,
 23330.981775305696,
 7813.111178407074,
 22982.49918313752,
 18794.207636911684,
 21108.492117685306,
 9519.980809227814,
 5081.346592256621,
 6697.344891515427,
 40454.044565981436,
 22798.973464565664,
 21059.11498994906,
 6578.64308369393,
 6147.7976285390005,
 26601.68184942938,
 50440.79888412978,
 36043.49345762922]

In [266]:
def calc_res(B: np.ndarray, Y: np.ndarray) -> float:
    Zreg = np.multiply(Y @ B, 1/np.dot(B, B))
    res = np.sum(((np.reshape(Zreg, (len(Zreg),1)) @ np.reshape(B, (1,len(B))) - np.mean(Y.flatten()))**2))
    return res

In [271]:
# R version:
# elif option == "simple":
    # Z.norm = apply(Z, 2, normF) 
    # B.norm = apply(B, 1, normF)
    # Z = sweep(Z, 2, Z.norm, "/")
    # B = sweep(B, 1, B.norm, "/")
    # res = (diag(t(Z) %*% Y %*% t(B))[1:k])^2

There is no `normF` function outside of the package `{fungible}`, which does not appear to be listed as a dependency.  I'm guessing it is supposed to be the Frobenius normal?

In [269]:
np.linalg.norm(Z, axis=1)

array([0.47065074, 0.39149962, 0.36557013, ..., 0.31422332, 0.42899943,
       0.40242758])

In [270]:
Z_norm = np.linalg.norm(Z, axis=1)
B_norm = np.linalg.norm(B, axis=0)

In [278]:
len(Z_norm)

5892

In [284]:
Z = np.divide(Z, np.reshape(Z_norm, (len(Z_norm),1)))
Z.head()

LV1       LV2       LV3       LV4       LV5       LV6  \
GAS6      0.000000  0.000000  0.065180  0.001635  0.267924  0.059560   
MMP14     0.019199  0.031926  0.000000  0.188189  0.700612  0.060812   
MARCKSL1  0.000000  0.000000  0.000000  0.000000  0.000000  0.169893   
SPARC     0.000000  0.000000  0.036919  0.000000  0.000000  0.012517   
CTSD      0.000000  0.151100  0.000000  0.000000  0.536046  0.000000   
...            ...       ...       ...       ...       ...       ...   
CFL2      0.206840  0.000000  0.030966  0.000000  0.000000  0.000000   
CFL1      0.000000  0.000000  0.000000  0.000000  0.351736  0.000000   
SELL      0.031354  0.504952  0.000000  0.063747  0.041554  0.093770   
GNGT2     0.000000  0.000000  0.000000  0.000000  0.250262  0.000000   
SERPINH1  0.000000  0.000000  0.053296  0.449537  0.000000  0.285350   

               LV7       LV8       LV9      LV10  ...      LV21      LV22  \
GAS6      0.000000  0.643492  0.010291  0.019948  ...  0.000000  0.108735   
MMP14     0.000000  0.101209  0.000000  0.000000  ...  0.129001  0.000000   
MARCKSL1  0.048469  0.000000  0.000000  0.000000  ...  0.295490  0.000000   
SPARC     0.016389  0.000000  0.014164  0.000000  ...  0.000000  0.000000   
CTSD      0.000000  0.000000  0.025347  0.000000  ...  0.000000  0.000000   
...            ...       ...       ...       ...  ...       ...       ...   
CFL2      0.305341  0.061290  0.419732  0.044949  ...  0.000000  0.000000   
CFL1      0.022876  0.001852  0.091779  0.000000  ...  0.084491  0.027163   
SELL      0.000000  0.000000  0.000000  0.198801  ...  0.178192  0.121683   
GNGT2     0.000000  0.000000  0.661852  0.000000  ...  0.000000  0.000000   
SERPINH1  0.000000  0.000000  0.514210  0.000000  ...  0.000000  0.018876   

              LV23      LV24      LV25      LV26      LV27      LV28  \
GAS6      0.000000  0.122313  0.088459  0.497868  0.199422  0.000000   
MMP14     0.227563  0.037854  0.450949  0.066254  0.000000  0.000000   
MARCKSL1  0.649931  0.000000  0.106737  0.000000  0.073635  0.282788   
SPARC     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
CTSD      0.601877  0.019443  0.000000  0.000000  0.061124  0.029772   
...            ...       ...       ...       ...       ...       ...   
CFL2      0.095376  0.042927  0.000000  0.321787  0.472807  0.000000   
CFL1      0.486628  0.115271  0.151292  0.000000  0.000000  0.261837   
SELL      0.000000  0.023631  0.000000  0.000000  0.594083  0.000000   
GNGT2     0.401584  0.000000  0.268894  0.215329  0.208118  0.000000   
SERPINH1  0.000000  0.295012  0.064689  0.000000  0.000000  0.132793   

              LV29      LV30  
GAS6      0.000000  0.000000  
MMP14     0.225612  0.280451  
MARCKSL1  0.000000  0.349431  
SPARC     0.000000  0.079054  
CTSD      0.000000  0.204620  
...            ...       ...  
CFL2      0.325551  0.359981  
CFL1      0.003116  0.242903  
SELL      0.192380  0.000000  
GNGT2     0.000000  0.311118  
SERPINH1  0.000000  0.207209  

[5892 rows x 30 columns]

In [280]:
B_norm = np.linalg.norm(B, axis=0)

In [283]:
B = np.divide(B, np.reshape(B_norm, (1,len(B_norm))))
B.head()

BD8001    BD8002    BD8003  \
1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  0.187167  0.009742  0.177031   
2,IRIS_Neutrophil-Resting                -0.134295 -0.253172  0.034137   
3,MIPS_SPLICEOSOME                       -0.013481 -0.203066  0.147269   
4,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY -0.245087 -0.224077  0.034288   
5,IRIS_Monocyte-Day0                      0.213247  0.041147 -0.135313   

                                            BD8004    BD8005    BD8006  \
1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  0.282832 -0.022828  0.183187   
2,IRIS_Neutrophil-Resting                 0.214181  0.319135 -0.072949   
3,MIPS_SPLICEOSOME                       -0.325909 -0.293837 -0.155963   
4,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  0.002501  0.122440  0.225361   
5,IRIS_Monocyte-Day0                      0.071167  0.222298  0.007611   

                                            BD8007    BD8008    BD8009  \
1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY -0.186647 -0.194501  0.052321   
2,IRIS_Neutrophil-Resting                -0.373122  0.218757 -0.485441   
3,MIPS_SPLICEOSOME                       -0.094047 -0.325233 -0.027035   
4,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY -0.156177  0.195204 -0.075764   
5,IRIS_Monocyte-Day0                      0.076949  0.131991 -0.237404   

                                            BD8010  ...    BD8031    BD8032  \
1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  0.259714  ...  0.216357 -0.018874   
2,IRIS_Neutrophil-Resting                -0.137368  ...  0.357107  0.053392   
3,MIPS_SPLICEOSOME                       -0.062867  ... -0.043913 -0.108791   
4,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY -0.282972  ...  0.017811 -0.610359   
5,IRIS_Monocyte-Day0                      0.207197  ...  0.144245 -0.157934   

                                            BD8033    BD8034    BD8038  \
1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  0.247088  0.146523  0.191068   
2,IRIS_Neutrophil-Resting                -0.255135 -0.596853  0.085961   
3,MIPS_SPLICEOSOME                       -0.265638 -0.200243  0.351928   
4,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  0.271412  0.321665  0.018983   
5,IRIS_Monocyte-Day0                     -0.051568 -0.058700 -0.056661   

                                            BD8041    BD8042    BD8043  \
1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY -0.020754  0.002584 -0.123099   
2,IRIS_Neutrophil-Resting                -0.507106  0.166998 -0.024483   
3,MIPS_SPLICEOSOME                        0.101598  0.323352  0.228680   
4,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  0.054268 -0.027263  0.165926   
5,IRIS_Monocyte-Day0                      0.030062 -0.566462  0.313470   

                                            BD8044    BD8045  
1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY -0.011695 -0.496100  
2,IRIS_Neutrophil-Resting                -0.067151  0.045032  
3,MIPS_SPLICEOSOME                       -0.161511  0.019439  
4,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY -0.097184 -0.059088  
5,IRIS_Monocyte-Day0                      0.234955  0.185153  

[5 rows x 36 columns]

In [ ]:
res = (
    diag(
        t(Z) %*% Y %*% t(B)
    )[1:k]
)^2

In [291]:
(np.diag(Z.T @ Y @ B.T)[:B.shape[0]])**2

array([ 4446422.00941171, 18027125.56030245,  3380605.10407671,
        2702855.84361412,  1462550.67258146,   793707.46889995,
       36129464.81298661,  1727203.3568754 ,   570915.40446368,
         267159.56269675,  1253282.6942452 ,  6447834.07985491,
         142828.56639562,   786708.90413462,   963731.43388324,
         158261.4692668 ,   416086.1120071 ,   366588.30026157,
         255690.93831038,   448765.6294822 ,    68865.75374871,
         151891.2936063 , 21865452.09755214,   109085.6734167 ,
         190629.93657325,    93758.27935025,   325928.11671604,
          89004.05460831,  5711875.32098239, 13816687.64466805])

In [292]:
# {R}
# else if (option == "project") {
#     res_temp <- c()
#     for (i in 1:k) {
#       Bk <- matrix(t(B[1:i, ]), ncol = i)
#       Xk <- Y %*% Bk %*% ginv(t(Bk) %*% Bk) %*% t(Bk)
#       res_temp <- c(res_temp, sum(diag(t(Xk) %*% Xk)))
#     } # for i
#     res <- res_temp
#     res[2:k] <- res[2:k] - res_temp[1:(k - 1)]

In [322]:
%%timeit
a = np.reciprocal(np.dot(B, B.T))

179 µs ± 1.15 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [323]:
%%timeit
b = 1/np.dot(B, B.T)

185 µs ± 787 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [305]:
def ginv(arr: np.ndarray) -> float:
    return 1/np.dot(arr, arr,)

In [315]:
%%timeit
ginv(B.iloc[1,:])

124 µs ± 1.63 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [311]:
def ginv2(arr: np.ndarray) -> float:
    return pinv(np.array([[np.dot(arr, arr)]]))

In [ ]:
%%timeit
ginv2(B.iloc[1,:])

220 µs ± 2.83 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
for i in range(k):
    Bk = B.iloc[0:i,:].transpose()
    Xk = Y @ Bk @ ginv(Bk.transpose @ Bk) @ Bk.transpose()
    res_temp = 
        c(
            res_temp,
            np.diag(Xk.T @ Xk).sum()
        )

In [330]:
res_temp = list()

In [331]:
i = 0

In [366]:
B.iloc[0:5,0:5]

BD8001    BD8002    BD8003  \
1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  0.999463  0.042062  1.265468   
2,IRIS_Neutrophil-Resting                -0.717132 -1.093098  0.244018   
3,MIPS_SPLICEOSOME                       -0.071986 -0.876761  1.052725   
4,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY -1.308753 -0.967479  0.245103   
5,IRIS_Monocyte-Day0                      1.138731  0.177655 -0.967259   

                                            BD8004    BD8005  
1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  2.361500 -0.068039  
2,IRIS_Neutrophil-Resting                 1.788295  0.951203  
3,MIPS_SPLICEOSOME                       -2.721166 -0.875800  
4,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  0.020884  0.364940  
5,IRIS_Monocyte-Day0                      0.594203  0.662572

In [368]:
Bk = B.iloc[:i+1,:].T

In [369]:
Bk.head()

1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY
BD8001                                  0.999463
BD8002                                  0.042062
BD8003                                  1.265468
BD8004                                  2.361500
BD8005                                 -0.068039

In [371]:
Bk.T @ Bk

1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY
1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY                                 49.250666

In [393]:
pinv(Bk.T @ Bk)[0][0]

0.020304294078741684

In [390]:
import scipy as sp

In [395]:
%%timeit
np.multiply(Y @ B.iloc[0,:], pinv(Bk.T @ Bk)[0])

888 µs ± 5.63 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [396]:
%%timeit
Y @ B.iloc[0,:] * pinv(Bk.T @ Bk)[0]

881 µs ± 31.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [399]:
Y @ Bk @ pinv(Bk.T @ Bk)[0]

GAS6       -0.461111
MMP14      -0.118825
MARCKSL1   -0.585187
SPARC      -0.181351
CTSD       -0.623603
              ...   
CFL2        0.377685
CFL1       -0.398598
SELL        0.301818
GNGT2      -0.261283
SERPINH1   -0.350007
Length: 5892, dtype: float64

In [410]:
Bk.values.T[0]

array([ 0.99946305,  0.0420622 ,  1.26546772,  2.36150025, -0.06803925,
        0.7711519 , -1.30416379, -0.67016881,  0.28786286,  1.33460189,
       -1.03493271, -0.23499556, -0.35511921, -0.81261244, -1.30316293,
       -1.73065182, -0.27861926,  0.73035592, -0.75220987, -2.53099625,
       -0.99492763,  0.43768905,  1.2975398 ,  0.30632185,  1.02331464,
        0.9493138 ,  1.49379582, -0.12278813,  1.04269436,  1.00028669,
        0.93142596, -0.10133202,  0.00838007, -0.49760019, -0.04114334,
       -3.44976462])

In [475]:
(Bk.values).flatten()

array([ 0.99946305,  0.0420622 ,  1.26546772,  2.36150025, -0.06803925,
        0.7711519 , -1.30416379, -0.67016881,  0.28786286,  1.33460189,
       -1.03493271, -0.23499556, -0.35511921, -0.81261244, -1.30316293,
       -1.73065182, -0.27861926,  0.73035592, -0.75220987, -2.53099625,
       -0.99492763,  0.43768905,  1.2975398 ,  0.30632185,  1.02331464,
        0.9493138 ,  1.49379582, -0.12278813,  1.04269436,  1.00028669,
        0.93142596, -0.10133202,  0.00838007, -0.49760019, -0.04114334,
       -3.44976462])

In [441]:
alpha = np.matmul(
    np.reshape(
        (Y @ Bk @ pinv(Bk.T @ Bk)[0]).values,
        (5892,1)
    ),
    np.reshape(
        Bk.values.T[0],
        (1,36)
    )
)

In [442]:
type(alpha)

numpy.ndarray

In [450]:
from icontract import ensure

In [451]:
@ensure(lambda a: a.ndim == 1, "a must be 1-d")
@ensure(lambda b: b.ndim == 1, "b must be 1-d")
def matmul1d(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return np.matmul(
        np.reshape(a, (len(a), 1)),
        np.reshape(b, (1, len(b)))
    )

In [452]:
beta = matmul1d(
    (Y @ Bk @ pinv(Bk.T @ Bk)[0]).values,
    Bk.values.T[0]
)

In [449]:
np.array_equal(alpha, beta)

True

In [456]:
Xk = matmul1d(
    (Y @ Bk @ pinv(Bk.T @ Bk)[0]).values,
    Bk.values.T[0],
)

In [457]:
Xk

array([[-0.46086358, -0.01939535, -0.58352131, ...,  0.22944901,
         0.01897165,  1.59072501],
       [-0.11876142, -0.00499805, -0.15036949, ...,  0.05912746,
         0.00488887,  0.40991907],
       [-0.58487322, -0.02461427, -0.74053581, ...,  0.29118938,
         0.02407657,  2.01875891],
       ...,
       [ 0.30165636,  0.01269515,  0.38194147, ..., -0.15018491,
        -0.01241782, -1.04120252],
       [-0.26114294, -0.01099015, -0.3306455 , ...,  0.13001459,
         0.01075007,  0.90136566],
       [-0.34981923, -0.01472207, -0.44292277, ...,  0.17416363,
         0.01440046,  1.20744235]])

In [461]:
np.diag(Xk.T @ Xk).sum()

48688.81382992759

In [476]:
def calc_project(a: np.ndarray, b: np.ndarray) -> float:
    Xk = matmul1d(
        (b @ a.T @ pinv(a @ a.T)[0]).values,
        a.flatten(),
    )
    return np.diag(Xk.T @ Xk).sum()

In [465]:
k = min(Y.shape[1], Y.shape[0], Z.shape[1], B.shape[0])

In [477]:
from tqdm.auto import tqdm, trange

In [478]:
k

30

In [480]:
project_res = [calc_project(B.iloc[:i+1].values, Y) for i in trange(k)]

  0%|          | 0/30 [00:00<?, ?it/s]

In [481]:
project_res

[48688.81382992759,
 138508.41322599913,
 173728.34632843375,
 200497.9059314099,
 226874.1099936003,
 252296.1044698464,
 186748.18998615257,
 201232.8557503429,
 210210.52339327574,
 211657.66142568458,
 217962.0684023598,
 235650.88833653566,
 244524.80045808962,
 253872.33069735434,
 262476.34388654924,
 272000.1924448643,
 286888.52775315,
 290926.31552010705,
 305400.0124661244,
 333552.3087936837,
 341480.3178555906,
 348065.6924137246,
 406058.6564492909,
 417498.7710783171,
 424242.81275630393,
 437001.23381630576,
 655493.4701584944,
 740397.867845162,
 816542.0042178265,
 9254701.699607927]

In [ ]:
for i in range(k):
    Bk = B.iloc[0:i,:].transpose()
    Xk = Y @ Bk @ ginv(Bk.transpose @ Bk) @ Bk.transpose()
    res_temp = 
        c(
            res_temp,
            np.diag(Xk.T @ Xk).sum()
        )

In [485]:
i = 1

In [486]:
Bk = B.iloc[:i+1,:].T

In [488]:
Bk.head()

1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  2,IRIS_Neutrophil-Resting
BD8001                                  0.999463                  -0.717132
BD8002                                  0.042062                  -1.093098
BD8003                                  1.265468                   0.244018
BD8004                                  2.361500                   1.788295
BD8005                                 -0.068039                   0.951203

In [515]:
Xk = np.matmul(
    (Y @ Bk @ pinv(Bk.T @ Bk)).values,
    Bk.values.T,
)

In [517]:
pd.DataFrame(Xk)

0         1         2         3         4         5         6   \
0    -0.464349 -0.025401 -0.581585 -1.077953  0.036585 -0.356919  0.586385   
1    -0.060352  0.095634 -0.182818 -0.464271 -0.079238 -0.069308  0.405982   
2    -0.509496  0.105251 -0.782411 -1.618940 -0.072874 -0.422459  1.087115   
3    -0.163167  0.023533 -0.239541 -0.485132 -0.014701 -0.132936  0.314238   
4    -0.627557 -0.033620 -0.786766 -1.459150  0.048842 -0.482532  0.794846   
...        ...       ...       ...       ...       ...       ...       ...   
5887  0.475454  0.184680  0.423521  0.583835 -0.172167  0.328698 -0.071527   
5888 -0.220212  0.290204 -0.603395 -1.501547 -0.239251 -0.239280  1.285539   
5889  0.031838 -0.452171  0.531836  1.561180  0.382849  0.129620 -1.553174   
5890 -0.120200  0.231838 -0.408945 -1.060210 -0.192935 -0.147619  0.946461   
5891 -0.178210  0.280941 -0.538258 -1.366162 -0.232745 -0.204318  1.193963   

            7         8         9   ...        26        27        28  \
0     0.312864 -0.147324 -0.618667  ... -0.674518  0.058476 -0.486245   
1     0.015263  0.210226 -0.103837  ... -0.416927 -0.016530 -0.032621   
2     0.309105  0.146985 -0.710341  ... -1.183130  0.031693 -0.492379   
3     0.101603  0.023485 -0.225079  ... -0.345040  0.012631 -0.160829   
4     0.422646 -0.197463 -0.836282  ... -0.913952  0.078856 -0.656930   
...        ...       ...       ...  ...       ...       ...       ...   
5887 -0.361082  0.518715  0.595889  ...  0.162586 -0.098575  0.546912   
5888  0.070774  0.630877 -0.364968  ... -1.325775 -0.045988 -0.137183   
5889  0.095083 -1.042258  0.149905  ...  1.556875  0.106700 -0.106946   
5890  0.019778  0.514605 -0.216603  ... -0.968045 -0.043012 -0.052185   
5891  0.045442  0.617399 -0.306270  ... -1.226288 -0.048457 -0.096774   

            29        30        31        32        33        34        35  
0    -0.483235 -0.426746  0.033030 -0.000875  0.228671  0.017650  1.590839  
1     0.249650 -0.156675  0.241522 -0.051077  0.072165  0.027030  0.408013  
2    -0.109795 -0.604420  0.355444 -0.069533  0.308014  0.052650  2.016299  
3    -0.067293 -0.183158  0.089436 -0.017027  0.094277  0.014317  0.625027  
4    -0.650845 -0.577462  0.046338 -0.001548  0.309347  0.024031  2.151422  
...        ...       ...       ...       ...       ...       ...       ...  
5887  0.995907  0.274631  0.346646 -0.080838 -0.166068  0.021599 -1.306123  
5888  0.725396 -0.511580  0.740406 -0.156108  0.238113  0.083940  1.369255  
5889 -1.400408  0.493610 -1.090665  0.233876 -0.210412 -0.114699 -1.032395  
5890  0.627864 -0.354362  0.580221 -0.123036  0.161475  0.064178  0.896765  
5891  0.732594 -0.461152  0.709697 -0.150074  0.212469  0.079453  1.201841  

[5892 rows x 36 columns]

In [509]:
(Y @ Bk @ pinv(Bk.T @ Bk)).values

array([[-0.46064382,  0.00551198],
       [-0.12665655, -0.09236277],
       [-0.59529375, -0.11919403],
       ...,
       [ 0.3379949 ,  0.42666599],
       [-0.28018041, -0.2228736 ],
       [-0.37301605, -0.27136712]])

In [512]:
Bk.values.T

array([[ 0.99946305,  0.0420622 ,  1.26546772,  2.36150025, -0.06803925,
         0.7711519 , -1.30416379, -0.67016881,  0.28786286,  1.33460189,
        -1.03493271, -0.23499556, -0.35511921, -0.81261244, -1.30316293,
        -1.73065182, -0.27861926,  0.73035592, -0.75220987, -2.53099625,
        -0.99492763,  0.43768905,  1.2975398 ,  0.30632185,  1.02331464,
         0.9493138 ,  1.49379582, -0.12278813,  1.04269436,  1.00028669,
         0.93142596, -0.10133202,  0.00838007, -0.49760019, -0.04114334,
        -3.44976462],
       [-0.71713166, -1.09309767,  0.24401848,  1.78829503,  0.95120262,
        -0.30709063, -2.60712838,  0.7537442 , -2.67083515, -0.70589913,
         3.41438102,  0.37662008, -3.01149785,  1.46766167,  1.84857172,
        -1.51660883,  1.82549595, -0.04070145,  2.04417929,  0.04209704,
         1.7028165 , -0.2497067 ,  0.08845836, -0.36762857,  0.47380526,
         0.14179317,  2.46558136,  0.34734906, -1.07665262, -4.07461568,
         0.41904572, -2.47597

In [493]:
(Y @ Bk).head()

1,REACTOME_GENERIC_TRANSCRIPTION_PATHWAY  2,IRIS_Neutrophil-Resting
GAS6                                    -22.710032                   2.426800
MMP14                                    -5.852222                  -7.903021
MARCKSL1                                -28.820871                  -8.395501
SPARC                                    -8.931645                  -1.843533
CTSD                                    -30.712846                   3.220938

In [496]:
pinv(Bk.T @ Bk)

array([[0.02038335, 0.00093239],
       [0.00093239, 0.01099658]])

In [495]:
sp.linalg.pinv(Bk.T @ Bk, )[0]

array([0.02038335, 0.00093239])

In [542]:
def calc_project(a: np.ndarray, b: np.ndarray) -> float:
    if a.shape[0] == 1:
        Xk = matmul1d(
            (b @ a.T @ pinv(a @ a.T)[0]).values,
            a.flatten(),
        )
    else:
        Xk = np.matmul(
            (b @ a.T @ pinv(a @ a.T)),
            a,
        )
    return np.diag(Xk.T @ Xk).sum()

In [528]:
B.iloc[:0+1].values.shape

(1, 36)

In [527]:
B.iloc[:1+1].values.shape

(2, 36)

In [534]:
i = 1

In [544]:
res = [calc_project(B.iloc[:i+1].values, Y) for i in trange(k)]

  0%|          | 0/30 [00:00<?, ?it/s]

In [545]:
res

[48688.81382992759,
 83734.80033666252,
 99861.17767181787,
 113410.9413453791,
 120159.40044003948,
 125845.06820925375,
 136720.19683199315,
 142602.6376195187,
 147018.5247882405,
 150705.4386127484,
 155389.11894102933,
 158728.32056373276,
 161232.4789140734,
 164540.88403359195,
 167454.13611074563,
 169871.7655592947,
 172452.6855329166,
 174669.15127501183,
 177440.70693424338,
 180667.53878046465,
 182643.46807285742,
 184997.56817000097,
 187888.37522993897,
 190066.7366024438,
 192032.67762029674,
 194161.35327598953,
 196311.09680970188,
 198263.16027038742,
 199616.81002059043,
 200984.85308909725]

In [482]:
from copy import deepcopy

In [546]:
res2 = deepcopy(res)

In [547]:
res[2:k] = res[2:k] - res2[0:(k - 1)]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [551]:
len(res[2:k])

28

In [550]:
len(res2[0:(k-1)])

29

In [555]:
np.append(res[0], ([x - y for x, y in zip(res[1:k], res[0:(k-1)])]))

array([48688.81382993, 35045.98650673, 16126.37733516, 13549.76367356,
        6748.45909466,  5685.66776921, 10875.12862274,  5882.44078753,
        4415.88716872,  3686.91382451,  4683.68032828,  3339.2016227 ,
        2504.15835034,  3308.40511952,  2913.25207715,  2417.62944855,
        2580.91997362,  2216.4657421 ,  2771.55565923,  3226.83184622,
        1975.92929239,  2354.10009714,  2890.80705994,  2178.3613725 ,
        1965.94101785,  2128.67565569,  2149.74353371,  1952.06346069,
        1353.6497502 ,  1368.04306851])